import { ContactSection, LinkItem, ProfessorAreaSection } from './types';

export const contactSections: ContactSection[] = [
  {
    id: 'secretaria',
    title: 'Secretaria de Pós-Graduação',
    contacts: [
      { name: 'Sara', email: 'spgipen@ipen.br', ramal: '1600' },
      { name: 'Rosana', email: 'ppgtn@cnen.gov.br', ramal: '5971' },
      { name: 'Bianca (Graduação e PAE)', email: 'ipen.pae@gmail.com', ramal: '1564' },
    ],
  },
  {
    id: 'bolsas',
    title: 'Setor de Bolsas, Ensino e IC',
    contacts: [
      { name: 'Elsa', email: 'eppsilva@ipen.br' },
      { name: 'Andressa', email: 'assantos-maxima@ipen.br' },
      { name: 'Ilze', email: 'ilze@ipen.br' },
      { name: 'Dra Martha', email: 'mmvieira@ipen.br' },
      { name: 'Geral', email: 'ceens@ipen.br' },
      { name: 'Alternativo', email: 'ceens.ensino@gmail.com' },
      { name: 'WhatsApp', details: '(11) 2810-5021', isWhatsapp: true },
    ],
  },
  {
    id: 'pae',
    title: 'Estágio PAE',
    contacts: [
        { name: 'Bianca', email: 'ipen.pae@gmail.com', ramal: '1564' },
    ],
  },
  {
    id: 'biblioteca',
    title: 'Biblioteca do Ipen',
    contacts: [
        { name: 'Email', email: 'bibl@ipen.br' },
        { name: 'WhatsApp', details: '(11) 99794-7917', isWhatsapp: true },
        { name: 'Verificação de Teses e Dissertações', email: 'verificateses@ipen.br', details: 'Fone: 2810-5797 (Bibliotecária Celia)' },
    ],
  },
  {
    id: 'cpg',
    title: 'Presidente CPG e Representantes Discentes',
    contacts: [
      { name: 'Prof. Dr. Julian Shorto (presidente)', email: 'jmshorto@ipen.br' },
      { name: 'Prof. Dr. Edson Moreira (vice-presidente)', email: 'emoreira@ipen.br' },
      { name: 'Ana Koka (Representante Discente)', email: 'anackoka.dfm@usp.br' },
      { name: 'Thais Andrade (Representante Discente)', email: 'thais.andradedasilva@usp.br' },
      { name: 'Silas Leonel (Representante Discente)', email: 'silasleonel@usp.br' },
      { name: 'Sabrina Sgrignoli (Representante Discente)', email: 'sabrinasgrignoli@usp.br' },
    ],
  },
];

export const linkItems: LinkItem[] = [
    {
        id: 'drive_docs',
        title: 'Drive de Documentos e Formulários',
        description: [
            'Formulários para matrículas e prorrogações.',
            'Modelos para teses e apresentações (templates).',
            'Documentos sobre exames de qualificação.',
            'Editais de bolsas e resultados.',
            'Procedimentos de depósito e defesa.',
        ],
        url: 'https://drive.google.com/drive/folders/1OdBhxH097PQZnm-Mu8NLFLu5w-u81n-G?usp=sharing'
    },
    {
        id: 'drive_bolsas',
        title: 'Drive de Editais de Bolsas',
        description: 'Editais vigentes e resultados.',
        url: 'https://drive.google.com/drive/folders/1IoXjFG0tW8YaF25vrgjfojuVRMRFtqN7?usp=sharing'
    },
    {
        id: 'proficiencia',
        title: 'Exame de Proficiência',
        description: 'Informações, editais e inscrições (FFLCH/USP).',
        url: 'https://clinguas.fflch.usp.br/proficiencia-ingles-editais-anexos-inscricoes-abertas'
    },
    {
        id: 'regimento_usp',
        title: 'Regimento da USP',
        description: 'Regimento Geral da Pós-Graduação da USP.',
        url: 'https://leginf.usp.br/?resolucao=resolucao-no-7493-de-27-de-marco-de-2018-copy'
    },
    {
        id: 'regimento_cpg',
        title: 'Regimento da CPG',
        description: 'Normas do programa de Tecnologia Nuclear.',
        url: 'https://www.prpg.usp.br/pt-br/prpg/index.php/pt-br/faca-pos-na-usp/programas-de-pos-graduacao/164-tecnologia-nuclear'
    }
];

export const professorSections: ProfessorAreaSection[] = [
  {
    id: 'TNR',
    title: 'TN-Reatores',
    fullName: 'Tecnologia Nuclear em Reatores',
    professors: [
      { name: 'Antonio Teixeira e Silva', lattesUrl: 'http://lattes.cnpq.br/0704015728319487', email: 'teixeira@ipen.br' },
      { name: 'Claudia Giovedi Motta', lattesUrl: 'http://lattes.cnpq.br/9625324106987116', email: 'claudia.giovedi@usp.br' },
      { name: 'Delvonei Alves de Andrade', lattesUrl: 'http://lattes.cnpq.br/4876508072951037', email: 'delvonei@usp.br' },
      { name: 'Frederico Antonio Genezini', lattesUrl: 'http://lattes.cnpq.br/2759618347264783', email: 'fredzini@ipen.br' },
      { name: 'Gaianê Sabundjian', lattesUrl: 'http://lattes.cnpq.br/4046461224135556', email: 'gdjian@ipen.br' },
      { name: 'Hélio Yoriyaz', lattesUrl: 'http://lattes.cnpq.br/2359603996065755', email: 'yoriyaz@usp.br' },
      { name: 'Julian Marco Barbosa Shorto', lattesUrl: 'http://lattes.cnpq.br/3190017636816434', email: 'jmshorto@ipen.br' },
      { name: 'Luís Alberto Pereira Dias', lattesUrl: 'http://lattes.cnpq.br/6348498331242654', email: 'lapdias@ipen.br' },
      { name: 'Marcelo da Silva Rocha', lattesUrl: 'http://lattes.cnpq.br/6939312723826719', email: 'marcelo.rocha@usp.br' },
      { name: 'Miguel Mattar Neto', lattesUrl: 'http://lattes.cnpq.br/7415302743715829', email: 'mmattar@usp.br' },
      { name: 'Roberto Navarro de Mesquita', lattesUrl: 'http://lattes.cnpq.br/9735321541608879', email: 'rnavarro@usp.br' },
      { name: 'Thadeu das Neves Conti', lattesUrl: 'http://lattes.cnpq.br/3751959240817368', email: 'tnconti@ipen.br' },
    ],
  },
  {
    id: 'TNA',
    title: 'TN-Aplicações',
    fullName: 'Tecnologia Nuclear em Aplicações',
    professors: [
        { name: 'Ademar José Potiens Junior', lattesUrl: 'http://lattes.cnpq.br/7767566901145853', email: 'apotiens@ipen.br' },
        { name: 'Artur Wilson Carbonari', lattesUrl: 'http://lattes.cnpq.br/0983858173807551', email: 'carbonar@usp.br' },
        { name: 'Bárbara Paci Mazzilli', lattesUrl: 'http://lattes.cnpq.br/5261926064717613', email: 'mazzilli@ipen.br' },
        { name: 'Carla Daruich de Souza', lattesUrl: 'http://lattes.cnpq.br/8451835458608326', email: 'cdsouza@usp.br' },
        { name: 'Carlos Alberto Zeituni', lattesUrl: 'http://lattes.cnpq.br/4079771121219968', email: 'czeituni@usp.br' },
        { name: 'Carlos Roberto Jorge Soares', lattesUrl: 'http://lattes.cnpq.br/3805602544840562', email: 'crjsoares@gmail.com' },
        { name: 'Cibele Bugno Zamboni', lattesUrl: 'http://lattes.cnpq.br/5738608742598468', email: 'bugnozamboni@gmail.com' },
        { name: 'Cibele Nunes Peroni', lattesUrl: 'http://lattes.cnpq.br/9157956641271272', email: 'cnperoni@ipen.br' },
        { name: 'Daniel Alexandre Baptista Bonifacio', lattesUrl: 'http://lattes.cnpq.br/0153111515550957', email: 'daniel.bonifacio@ipen.br' },
        { name: 'Daniel Perez Vieira', lattesUrl: 'http://lattes.cnpq.br/7801475936103703', email: 'dperezv@usp.br' },
        { name: 'Edson Gonçalves Moreira', lattesUrl: 'http://lattes.cnpq.br/5179535565063558', email: 'edson.moreira@usp.br' },
        { name: 'Elaine Bortoleti de Araújo', lattesUrl: 'http://lattes.cnpq.br/4921659299780500', email: 'ebaraujo@ipen.br' },
        { name: 'Emerson Soares Bernardes', lattesUrl: 'http://lattes.cnpq.br/2599156909197631', email: 'emerson.bernardes@gmail.com' },
        { name: 'Júlio Takehiro Marumo', lattesUrl: 'http://lattes.cnpq.br/1242074276348655', email: 'jtmarumo@ipen.br' },
        { name: 'Leonardo Gondim de Andrade e Silva', lattesUrl: 'http://lattes.cnpq.br/7388174990363675', email: 'lgasilva@ipen.br' },
        { name: 'Linda Viola Ehlin Caldas', lattesUrl: 'http://lattes.cnpq.br/2032000100824080', email: 'lcaldas@ipen.br' },
        { name: 'Maria da Conceição Costa Pereira', lattesUrl: 'http://lattes.cnpq.br/0977986453736808', email: 'macoper@ipen.br' },
        { name: 'Maria da Penha Albuquerque Potiens', lattesUrl: 'http://lattes.cnpq.br/2413622335075405', email: 'mppalbu@ipen.br' },
        { name: 'Maria Elisa Chuery Martins Rostelato', lattesUrl: 'http://lattes.cnpq.br/4947891787244417', email: 'elisaros@ipen.br' },
        { name: 'Mário Olímpio de Menezes', lattesUrl: 'http://lattes.cnpq.br/4882949829423994', email: 'momenezes@usp.br' },
        { name: 'Mauro da Silva Dias', lattesUrl: 'http://lattes.cnpq.br/6758486812739598', email: 'maurosilvadias@gmail.com' },
        { name: 'Monica Beatriz Mathor', lattesUrl: 'http://lattes.cnpq.br/0655717478478500', email: 'mathor@ipen.br' },
        { name: 'Nélida Lúcia Del Mastro', lattesUrl: 'http://lattes.cnpq.br/8541245790089233', email: 'nelida@usp.br' },
        { name: 'Orlando Rodrigues Junior', lattesUrl: 'http://lattes.cnpq.br/4497027431723360', email: 'rodrijr@ipen.br' },
        { name: 'Pablo Antonio Vasquez Salvador', lattesUrl: 'http://lattes.cnpq.br/6500252259164928', email: 'pavsalva@usp.br' },
        { name: 'Paolo Bartolini', lattesUrl: 'http://lattes.cnpq.br/3737390739124657', email: 'pbartoli@ipen.br' },
        { name: 'Patrick Jack Spencer', lattesUrl: 'http://lattes.cnpq.br/2173085213526010', email: 'pspencer@ipen.br' },
        { name: 'Paulo Sergio Cardoso da Silva', lattesUrl: 'http://lattes.cnpq.br/2223288359945590', email: 'pscsilva@ipen.br' },
        { name: 'Renato Semmler', lattesUrl: 'http://lattes.cnpq.br/6798717991999373', email: 'rsemmler@ipen.br' },
        { name: 'Sandra Regina Damatto', lattesUrl: 'http://lattes.cnpq.br/8730802405611979', email: 'damatto@ipen.br' },
        { name: 'Solange Kazumi Sakata', lattesUrl: 'http://lattes.cnpq.br/7715634436402530', email: 'solange.sakata@usp.br' },
        { name: 'Valter Arthur', lattesUrl: 'http://lattes.cnpq.br/4352244824716787', email: 'arthur@cena.usp.br' },
        { name: 'Wilson Aparecido Parejo Calvo', lattesUrl: 'http://lattes.cnpq.br/2124222210630317', email: 'wapcalvo@ipen.br' },
        { name: 'Yasko Kodama', lattesUrl: 'http://lattes.cnpq.br/5466500131592834', email: 'yasko.kodama@gmail.com' },
    ],
  },
  {
    id: 'TNM',
    title: 'TN-Materiais',
    fullName: 'Tecnologia Nuclear em Materiais',
    professors: [
      { name: 'Ademar Benévolo Lugão', lattesUrl: 'http://lattes.cnpq.br/8256644098407834', email: 'ablugao@gmail.com' },
      { name: 'Almir Oliveira Neto', lattesUrl: 'http://lattes.cnpq.br/3793709708793934', email: 'aolivei@ipen.br' },
      { name: 'Anderson Zanardi de Freitas', lattesUrl: 'http://lattes.cnpq.br/7935699829401769', email: 'freitas.az@alumni.usp.br' },
      { name: 'Antonio Augusto Couto', lattesUrl: 'http://lattes.cnpq.br/2893737202813850', email: 'acouto@mackenzie.br' },
      { name: 'Cecilia Chaves Guedes e Silva', lattesUrl: 'http://lattes.cnpq.br/3598507725109908', email: 'cecilia.guedes@ipen.br' },
      { name: 'Cristiano Stefano Mucsi', lattesUrl: 'http://lattes.cnpq.br/2583729137737338', email: 'csmucsi@ipen.br' },
      { name: 'Denise Alves Fungaro', lattesUrl: 'http://lattes.cnpq.br/8846838825034067', email: 'dfungaro@ipen.br' },
      { name: 'Denise Maria Zezell', lattesUrl: 'http://lattes.cnpq.br/3524890504250775', email: 'zezell@usp.br' },
      { name: 'Dolores Ribeiro Ricci Lazar', lattesUrl: 'http://lattes.cnpq.br/4289995849705434', email: 'drlazar@ipen.br' },
      { name: 'Duclerc Fernandes Parra', lattesUrl: 'http://lattes.cnpq.br/1691114842151172', email: 'dfparra@ipen.br' },
      { name: 'Eduardo Landulfo', lattesUrl: 'http://lattes.cnpq.br/2559423762888504', email: 'landulfo@usp.br' },
      { name: 'Eliana Navarro dos Santos Muccillo', lattesUrl: 'http://lattes.cnpq.br/8056347635021792', email: 'enavarro@usp.br' },
      { name: 'Elisabete Inácio Santiago', lattesUrl: 'http://lattes.cnpq.br/4409120770460899', email: 'eisantia@ipen.br' },
      { name: 'Elita Fontenele Urano de Carvalho', lattesUrl: 'http://lattes.cnpq.br/1122522095905469', email: 'elitaucf@ipen.br' },
      { name: 'Esperidiana Augusta Barretos de Moura', lattesUrl: 'http://lattes.cnpq.br/3762319173348289', email: 'eabmoura@ipen.br' },
      { name: 'Fabio Coral Fonseca', lattesUrl: 'http://lattes.cnpq.br/2790158217446989', email: 'fabiocf@usp.br' },
      { name: 'Isolda Costa', lattesUrl: 'http://lattes.cnpq.br/3336529728610160', email: 'isolda.costa@usp.br' },
      { name: 'Jesualdo Luiz Rossi', lattesUrl: 'http://lattes.cnpq.br/0763948174052925', email: 'jelrossi@ipen.br' },
      { name: 'Jorge Eduardo de Souza Sarkis', lattesUrl: 'http://lattes.cnpq.br/5455867834427820', email: 'jesarkis@hotmail.com' },
      { name: 'Jose Fernando Diniz Chubaci', lattesUrl: 'http://lattes.cnpq.br/8766146745773566', email: 'chubaci@usp.br' },
      { name: 'Jose Oscar William Vega Bustillos', lattesUrl: 'http://lattes.cnpq.br/6677363162414640', email: 'ovega@ipen.br' },
      { name: 'Larissa Otubo', lattesUrl: 'http://lattes.cnpq.br/6695878471185106', email: 'larissa.otubo@ipen.br' },
      { name: 'Luciana Vanni Gatti', lattesUrl: 'http://lattes.cnpq.br/6983900937588878', email: 'lvgatti@ipen.br' },
      { name: 'Luís Antonio Genova', lattesUrl: 'http://lattes.cnpq.br/5674887772256354', email: 'lgenova@ipen.br' },
      { name: 'Luis Gallego Martinez', lattesUrl: 'http://lattes.cnpq.br/6869198419648078', email: 'lgmartinez@usp.br' },
      { name: 'Marcus Paulo Raele', lattesUrl: 'http://lattes.cnpq.br/5900133044656035', email: 'mpraele@ipen.br' },
      { name: 'Maria Claudia França da Cunha Felinto', lattesUrl: 'http://lattes.cnpq.br/1623651835700843', email: 'mfelinto@ipen.br' },
      { name: 'Marina Fuser Pillis', lattesUrl: 'http://lattes.cnpq.br/6515399745840330', email: 'mfpillis@ipen.br' },
      { name: 'Martha Simões Ribeiro', lattesUrl: 'http://lattes.cnpq.br/4996734160632011', email: 'marthasr@usp.br' },
      { name: 'Marycel Elena Barboza Cotrim', lattesUrl: 'http://lattes.cnpq.br/9968341630176283', email: 'mecotrim@ipen.br' },
      { name: 'Maurício David Martins das Neves', lattesUrl: 'http://lattes.cnpq.br/4302742485642568', email: 'mdmneves@gmail.com' },
      { name: 'Michelangelo Durazzo', lattesUrl: 'http://lattes.cnpq.br/1329671245559098', email: 'mdurazzo@ipen.br' },
      { name: 'Nelson Batista de Lima', lattesUrl: 'http://lattes.cnpq.br/6675251190520162', email: 'nblima22@gmail.com' },
      { name: 'Niklaus Ursus Wetter', lattesUrl: 'http://lattes.cnpq.br/8623798867256227', email: 'nuwetter@ipen.br' },
      { name: 'Nilce Ortiz', lattesUrl: 'http://lattes.cnpq.br/0002489527100475', email: 'nortiz@ipen.br' },
      { name: 'Rafael Henrique Lazzari Garcia', lattesUrl: 'http://lattes.cnpq.br/4311312149706721', email: 'teo@usp.br' },
      { name: 'René Ramos de Oliveira', lattesUrl: 'http://lattes.cnpq.br/0652596404798980', email: 'rolivier@ipen.br' },
      { name: 'Ricardo Elgul Samad', lattesUrl: 'http://lattes.cnpq.br/9343283105180098', email: 'resamad@gmail.com' },
      { name: 'Ricardo Mendes Leal Neto', lattesUrl: 'http://lattes.cnpq.br/3270615314717988', email: 'riclealn@usp.br' },
      { name: 'Rubens Nunes de Faria Júnior', lattesUrl: 'http://lattes.cnpq.br/8776524631256060', email: 'rfaria@ipen.br' },
      { name: 'Sabine Neusatz Guilhen', lattesUrl: 'http://lattes.cnpq.br/2468258240854998', email: 'snguilhen@ipen.br' },
      { name: 'Wagner de Rossi', lattesUrl: 'http://lattes.cnpq.br/7755548478382164', email: 'wderossi@gmail.com' },
    ],
  },
];